Repository microsoft/MicroHack, pull requests merged in 2023-10, with the labels that each got.

#91 Last PR - AVD MicroHack 10/2023
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Challenges/02-Create-a-custom-golden-image.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Solutionguide/02-Create-a-custom-golden-image.md
Labels: documentation

#92 Adjust Deployment to be able to be individually or batch deployed
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/destination.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/main.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
Labels: technical

#93 Azure Monitor - Fix issues
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/README.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/challenges/00_challenge.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/challenges/01_challenge.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/challenges/02_challenge.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/challenges/03_challenge.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/challenges/05_challenge.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/img/architecture_01.png
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/scripts/challenge-5/create-custom-table.ps1
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/scripts/challenge-5/generate-logs.ps1
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/scripts/challenge-5/sample-data.json
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/app-gw.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/bastion.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/modules/vms/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/modules/vms/outputs.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/modules/vms/variables.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/network.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/outputs.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/variables.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/vmss.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/web.conf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/locals.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/modules/vms/variables.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/providers.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/variables.tf
Labels: documentation, technical

#94 Fixes after Walkthrough
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/solution.md
Labels: documentation, technical

#101 Fixed Task numbering in Migration Microhack walkthrough
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/solution.md
Labels: bug, documentation

#102 Add Output of Identifier to Bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/main.bicep
Labels: bug, technical

#103 Add required quota information to the deployment README
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/README.md
Labels: documentation

#104 Fix issue #99
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/img/azreplapl4.png
Labels: documentation

#105 Fix Issue #97
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-2/img/Discover15.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-2/img/Discover16.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-2/img/Discover17.png
Labels: documentation
