Repository microsoft/MicroHack, pull requests merged in 2023-09, with the labels that each got.

#76 Add hint to challenge #5 to initialize data disk before it can be used
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/solution.md
Labels: documentation

#77 Update Mobility Service Installation Parameters
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/img/maw3-1.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/img/maw3-2.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/solution.md
Labels: documentation

#75 MicroHack Migration add capability to deploy multiple instances
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/destination.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/main.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
Labels: feature, technical

#72 Add Template to Link MicroHack
  99-MicroHack-TemplateLink/Readme.md
  CONTRIBUTING.md
Labels: documentation

#74 ADX context added
  03-Azure/01-02 Data/02-ADX-Microhack/readme.md
Labels: documentation, linked

#80 Use clear visuals for Alerts
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/Readme.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/solution.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-2/solution.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-3/solution.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-4/solution.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-5/solution.md
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-6/solution.md
Labels: documentation

#82 Update CONTRIBUTING with alerts an restructure
  CONTRIBUTING.md
Labels: documentation

#86 Update Issue Template with new MicroHacks
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/featurerequest.yaml
Labels: technical

#88 MH AVD - Rollback Challenge 2
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Challenges/02-Create-a-custom-golden-image.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Challenges/Archive/02-Create-a-custom-golden-image-new.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Challenges/Archive/02-Create-a-custom-golden-image.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Readme.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Solutionguide/02-Create-a-custom-golden-image.md
  03-Azure/01-03-Infrastructure/01_Azure_Virtual_Desktop/Solutionguide/Archive/02-Create-a-custom-golden-image-solution-new.md
Labels: bug, documentation
