Repository microsoft/MicroHack, pull requests merged in 2024-03, with the labels that each got.

#142 updated arc-enabled-servers
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/ChangeTracking/template-DCR-ChangeTracking.json
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/README.md
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/create_vms.sh
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/parameters-lnx.json
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/parameters-win.json
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/reconfig-ubuntu.sh
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/reconfig-win.ps1
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/template-lnx.json
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/resources/demo-vm-creator/template-win.json
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-1/solution.md
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/2.3_Create_Data_Collection_Rule_Basics.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/3.5_Assign_Policy_Monitor_AMA_remidiate.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/3.6_Assign_Policy_Monitor_AMA_remidiate.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/3.7_Assign_Policy_Monitor_AMA_remidiate.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/5.1_remediation_tasks.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/img/5.9_Inventory.png
  03-Azure/01-03-Infrastructure/02_Hybrid_Azure_Arc_Servers/walkthrough/challenge-2/solution.md
Labels: documentation, technical

#145 Migrate and Modernize deployment update
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/destination.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/main.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS1-1.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS1.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS2.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS3.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS4.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS5.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS6.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/img/CS7.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/solution.md
Labels: documentation, technical

#144 MH Monitor - deployment hints / terraform parameterization
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/Readme.md
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/app-gw.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/bastion.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/locals.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/modules/vms/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/modules/vms/variables.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/network.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/variables.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/enviornment/vmss.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/locals.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/main.tf
  03-Azure/01-03-Infrastructure/07_Azure_Monitor/resources/terraform/variables.tf
Labels: documentation, technical

#148 Update Deployment command to support any display name
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/walkthrough/challenge-1/solution.md
Labels: documentation, technical

#149 Update Keyvaultname
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
Labels: bug

#151 Update Demo Page for Migration Servers
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/GitHub_Logo.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/MSLogo.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/MSicon.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/github-mark.png
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/index.html
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/demopage/stylesheet.css
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/deploy.ps1
  03-Azure/01-03-Infrastructure/06_Migration_Datacenter_Modernization/resources/source.bicep
Labels: technical
